# Generated by Django 2.2.6 on 2019-10-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('fax', models.CharField(max_length=10)),
                ('has_pool', models.BooleanField()),
                ('has_gym', models.BooleanField()),
                ('has_free_breakfast', models.BooleanField()),
                ('has_restaurant', models.BooleanField()),
                ('general_manager', models.CharField(max_length=50)),
                ('manager_email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('parking_lot_id', models.AutoField(primary_key=True, serialize=False)),
                ('lot_name', models.CharField(max_length=50)),
                ('floors', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=8)),
                ('room_floor', models.IntegerField()),
                ('room_type', models.CharField(max_length=20)),
                ('has_balcony', models.BooleanField()),
                ('room_rate_nightly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_rate_weekly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkin_date', models.DateTimeField()),
                ('checkout_date', models.DateTimeField()),
                ('total_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Room')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('parking_space_id', models.AutoField(primary_key=True, serialize=False)),
                ('space_number', models.CharField(max_length=10)),
                ('license_plate', models.CharField(max_length=10)),
                ('car_make', models.CharField(max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotelapp.Customer')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.ParkingLot')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotelapp.Room')),
            ],
        ),
    ]
